### ISSUE TITLE
Where is the decrpyted save stored?

### ISSUE THREAD

**Issue by xFN10x** [bucanero/save-decrypters#9]
I have decrpyted a save, and i have no idea where the decrpyted save goes.

**Comment by bucanero** [comment]
which decrypter are you referring to?

in most cases, the decrypted data is stored in the same file, and a backup `.bak` file is created.

E.g., decrypting `SAVEDATA.BIN` , will store decrypted data to `SAVEDATA.BIN`, and keep the original backup as `SAVEDATA.BIN.bak`

**Comment by xFN10x** [comment]
mgsv-tpp and also, doesnt mgsv have mulitble files that have data in them?

**Comment by xFN10x** [comment]
Also, do i use MGSVTPPSaveDataNA.bin or MGSVTPPSaveDataNA? (no file extension)

**Comment by bucanero** [comment]
These decryption tools are only for the custom encryption layer, it won't work over PS4 system encryption 

You need a jailbroken PS4 to extract the internal save data files, then you can use this MGS5 decrypter.
